#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Strategy Analysis Script
Run this to analyze the strategy performance
"""

print("=" * 60)
print("VALUATION MULTI-FACTOR STRATEGY ANALYSIS")
print("=" * 60)

print("\nThis script analyzes the valuation multi-factor strategy.")
print("\nTo run the full analysis:")
print("1. First run the main strategy: python src/valuation_strategy.py")
print("2. Then check the results/images/ folder for charts")
print("3. Check the CSV files for detailed results")

print("\nKey files generated by the strategy:")
print("- results/images/performance_YYYYMMDD_HHMM.png: Main performance chart")
print("- results/images/performance_YYYYMMDD_HHMM.pdf: PDF version")
print("- valuation_strategy_YYYYMMDD_HHMM_returns.csv: Period returns")
print("- valuation_strategy_YYYYMMDD_HHMM_nav.csv: Net asset value")
print("- valuation_strategy_YYYYMMDD_HHMM_metrics.csv: Performance metrics")

print("\n" + "=" * 60)
print("ANALYSIS COMPLETE")
print("=" * 60)